version: '2.0'
services:
  newsletterservice:
    image: newsletterservice:latest
    ports:
      - "8081:8081"

  accountservice:
    image: accountservice:latest
    ports:
      - "8080:8080"
    environment:
      - "CONFIG=ci.conf"
      - "NEWSLETTER_HOST=newsletterservice"
    links:
      - "newsletterservice"

